CAB = "cab"
ICAB = "icab"
DET = "det"
IDET = "idet"
PDBC = "pdbc"
PDBC_STOTA = "pdbc_stota"
PDBF = "pdbf"
DA_CLEAR = "marginalpdbc"
INDISP = "indisp"
UNIT_CURVES = "curva_pbc_uof"

_endpoints = {
    DA_CLEAR: {
        "raw_data_type": "text",
        "frequency": "daily",
        "text_format": "csv",
        "filespec": {
            "skiplines": 1,
            "skipfooter": 1,
            "colnames": ["year", "month", "day", "hour", "pt", "es", "notused"],
        },
    },
    PDBC_STOTA: {
        "raw_data_type": "text",
        "frequency": "daily",
        "text_format": "csv",
        "filespec": {
            "skiplines": 3,
            "skipfooter": 1,
            "colnames": [
                "code",
                "field",
                "country",
                "HE1",
                "HE2",
                "HE3",
                "HE4",
                "HE5",
                "HE6",
                "HE7",
                "HE8",
                "HE9",
                "HE10",
                "HE11",
                "HE12",
                "HE13",
                "HE14",
                "HE15",
                "HE16",
                "HE17",
                "HE18",
                "HE19",
                "HE20",
                "HE21",
                "HE22",
                "HE23",
                "HE24",
                "HE25",
                "notused",
            ],
        },
    },
    CAB: {
        "raw_data_type": "zipfile",
        "frequency": "monthly",
        "text_format": "fwf",
        "filespec": {
            "colspecs": [
                (0, 7),
                (7, 10),
                (10, 17),
                (17, 47),
                (47, 48),
                (48, 49),
                (49, 50),
                (50, 67),
                (67, 84),
                (84, 91),
                (91, 98),
                (98, 115),
                (115, 132),
                (132, 139),
                (139, 146),
                (146, 153),
                (153, 155),
                (155, 159),
                (159, 161),
                (161, 163),
                (163, 165),
                (165, 167),
                (167, 169),
            ],
            "colnames": [
                "offer_code",
                "version",
                "code",
                "description",
                "cv",
                "notused",
                "offer_deadline",
                "notused1",
                "notused2",
                "max_ramp_up",
                "max_ramp_down",
                "fixed_term",
                "variable_term",
                "max_power",
                "startup_ramp",
                "shutdown_ramp",
                "interconnection_code",
                "offer_year",
                "offer_month",
                "offer_day",
                "offer_hour",
                "offer_minute",
                "offer_second",
            ],
        },
    },
    # TODO: Docs are incorrect on fixed width format. Need to suss this out independently
    ICAB: {
        "raw_data_type": "zipfile",
        "frequency": "monthly",
        "text_format": "fwf",
        "filespec": {
            "colspecs": [
                (2, 9),
                (9, 12),
                (12, 19),
                (19, 22),
                (22, 52),
                (52, 53),
                (53, 54),
                (54, 55),
                (55, 59),
                (59, 65),
                (66, 73),
                (73, 80),
                (80, 87),
                (87, 94),
                (94, 101),
                (101, 135),
                (135, 152),
                (152, 169),
                (169, 170),
                (170, 177),
                (177, 179),
                (179, 193),
                (193, 194),
            ],
            "colnames": [
                "offer_code",
                "version",
                "code",
                "offer_number",
                "description",
                "cv",
                "offer_type",
                "international",
                "type_of_need",
                "max_ramp_up",
                "max_ramp_down",
                "startup_ramp",
                "shutdown_ramp",
                "min_stable_level",
                "max_energy",
                "not_utilized",
                "fixed_term",
                "variable_term",
                "is_withdrawable",
                "max_potential_energy",
                "min_consecutive_hours",
                "last_modified",
                "is_withdrawn",
            ],
        },
    },
    DET: {
        "raw_data_type": "zipfile",
        "frequency": "monthly",
        "text_format": "fwf",
        "filespec": {
            "colspecs": [
                (0, 7),
                (7, 10),
                (10, 12),
                (12, 14),
                (14, 31),
                (31, 48),
                (48, 55),
                (55, 56),
                (56, 57),
            ],
            "colnames": [
                "offer_code",
                "version",
                "period",
                "block_number",
                "notused",
                "price",
                "volume",
                "divisible_block_indicator",
                "removable_block_indicator",
            ],
        },
    },
    # TODO: Docs are incorrect on fixed width format. Need to suss this out independently
    IDET: {
        "raw_data_type": "zipfile",
        "frequency": "monthly",
        "text_format": "fwf",
        "filespec": {
            "colspecs": [
                (0, 7),
                (7, 10),
                (10, 17),
                (17, 20),
                (20, 24),
                (24, 26),
                (26, 28),
                (28, 30),
                (30, 32),
                (32, 49),
                (49, 66),
                (67, 74)
            ],
            "colnames": [
                "offer_code",
                "version",
                "unit_code",
                "offer_number"
                "offer_year",
                "offer_month",
                "offer_day",
                "offer_hour",
                "block_number",
                "notused",
                "offer_price",
                "offer_volume"
            ],
        },
    },
    PDBC: {
        "raw_data_type": "zipfile",
        "frequency": "monthly",
        "text_format": "csv",
        "filespec": {
            "skiplines": 1,
            "skipfooter": 1,
            "colnames": [
                "year",
                "month",
                "day",
                "hour",
                "unit_code",
                "assigned_energy",
                "notused",
                "offer_type",
                "offer_code",
                "notused2",
            ],
        },
    },
    INDISP: {"frequency": "monthly"},
    UNIT_CURVES: {
        "raw_data_type": "zipfile",
        "frequency": "monthly",
        "text_format": "csv",
        "filespec": {
            "skiplines": 3,
            "skipfooter": 1,
            "colnames": [
                "hour",
                "date",
                "country",
                "unit_code",
                "offer_type",
                "volume",
                "price",
                "bid_offer",
                "notused",
            ],
        },
    },
    PDBF: {
        "raw_data_type": "zipfile",
        "frequency": "monthly",
        "text_format": "csv",
        "filespec": {
            "skiplines": 1,
            "skipfooter": 1,
            "colnames": [
                "year",
                "month",
                "day",
                "hour",
                "unit_code",
                "assigned_energy",
                "bilateral_counterparty_id",
                "offer_type",
                "offer_number",
                "notused",
            ],
        },
    },
}
